Basic Package Information:
    Name: "dotstartemplatepackage"
Compilation Information:
    Ignore files:
        - .git*
        - .vscode*
        - DotStarTemplatePackage.star
Author information:
    Name: "joachimschmidt557"
    Company: ""
    Website: "https://github.com/joachimschmidt557"
    Email: ""
Application Information: 
    Name: "DotStarTemplatePackage"
    Friendly Name: "DotStar Template Package"
    Description: "A simple testing package to check wheter DotStar works"
    Version: "1.0.0"
    Version System: "MajorMinor"
    Supported Platforms:
        - MacOS
        - Win32
        - Win64
        - Linux
Dependencies:
    - 
        Name: "Python3"
        File: "Python3.star"